//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionmateriales.Models.GestionMateriales
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public int idMaterial { get; set; }
        public int cantidad { get; set; }
        public string nombre { get; set; }
        public int stockMinimo { get; set; }
        public int pedido_nroPedido { get; set; }
        public int proveedor_idProveedor { get; set; }
        public int unidad_idUnidad { get; set; }
    }
}
