//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionmateriales.Models.GestionMateriales
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pp67_gestionmaterialesEntities : DbContext
    {
        public pp67_gestionmaterialesEntities()
            : base("name=pp67_gestionmaterialesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<clasematerial> clasematerial { get; set; }
        public DbSet<entrada> entrada { get; set; }
        public DbSet<material> material { get; set; }
        public DbSet<pedido> pedido { get; set; }
        public DbSet<personal> personal { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<salida> salida { get; set; }
        public DbSet<unidad> unidad { get; set; }
    }
}
