//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionmateriales.Models.GestionMateriales
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int nroPedido { get; set; }
        public int nroOrdenDeTrabajo { get; set; }
        public string destino { get; set; }
    }
}
