// <auto-generated />
namespace gestionmateriales.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seguridad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seguridad));
        
        string IMigrationMetadata.Id
        {
            get { return "201802261825493_seguridad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
